# Config file for automatic testing at travis-ci.org
sudo: false

language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.3 ]]; then pip install virtualenv==15.1.0; fi
  - pip install tox coverage codecov
  - coverage erase

# command to run tests, e.g. python setup.py test
script: tox -e py

after_success:
    - coverage combine
    # Report coverage results to codecov.io
    - codecov
